<?php

namespace Sistema\SisreimpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * tipoVehiculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipoVehiculoRepository extends EntityRepository
{
}
