<?php

namespace Sistema\SisreimpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VehiculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculoRepository extends EntityRepository {

    static function impuestoVehiculo($id_ve, $id_ti) {
        $em = $this->getDoctrine()->getManager();
        $entities_vh = $em->getRepository('SistemaSisreimpBundle:Vehiculo')->find($id_ve);
        $monto= $entities_vh->getCosto();
        $tipo= $entities_vh->getTipo();
        
        return $monto;        
        
        
        
        $entities_tipo = $em->getRepository('SistemaSisreimpBundle:TipoVehiculos')->find($id_ti);
    }

}
