parameters:
#    espectaculos_publicos.example.class: Espectaculos\PublicosBundle\Example

services:
#    espectaculos_publicos.example:
#        class: %espectaculos_publicos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
